### ISSUE TITLE
The launch file fails to initialize haptic device.

### ISSUE THREAD

**Issue by mjm522** [fsuarez6/phantom_omni#2]
Hi, 

I followed the instructions to install the Phantom Omni. I am able to run both PHANToMConfiguration and PHANToMTest successfully. However after building this ros-package, I am getting the following error on launching the omni.launch file.

`
ERROR] [1520379495.119316581]: Failed to initialize haptic device`

Could you please provide any guidance on solving this?

I am on Ubuntu 14.04 with Indigo.

Best,

Mike

**Comment by mjm522** [comment]
Hi

I fixed the issue. Got it running.

This is what you have to do.

Step 1: in the omni.cpp define a macro name

#define DEVICE_NAME "Default PHANToM"

Step 2: line 302 in omni.cpp change to

hHD = hdInitDevice(DEVICE_NAME);

Step 3: run the roslaunch as root!

Everything works!

My reasoning: HD_DEFAULT_DEVICE is a HDString and it is set as NULL by default, somehow this is causing the problem since the API is trying to access a NULL value. So we need to set the actual name of the device. This should be a bug in the API.

**Comment by deepakraina99** [comment]
@mjm522 I am still getting the same error after doing the above mentioned steps
